### ISSUE TITLE
HOL-Ex3-Task1-Step3 - Azure CLI command error

### ISSUE THREAD

**Issue by rodrigoffonseca** [Microsoft/MCW-Linux-lift-and-shift#10]
I got the following error during Ex3, task 1 step 3 of HOL lab:
C:\Users\rfonseca>az mysql server create --resource-group OsTicketPaaSRG --name foca-osticketsrv01 --location "West US" --admin-user demouser --admin-password demo@pass123 --sku-name B_Gen4_1 --storage-size 51200 --ssl-enforcement Disabled
az mysql server create: error: unrecognized argument: --sku-name B_Gen4_1

I managed to successfully deploy using this command:

C:\Users\rfonseca>az mysql server create --resource-group OsTicketPaaSRG --name foca-osticketsrv01 --location "West US" --admin-user demouser --admin-password demo@pass123 --performance-tier Basic --storage-size 51200 --ssl-enforcement Disabled

**Comment by DawnmarieDesJardins** [comment]
Hi Michael, please review and make sure this was resolved with the September test/fix I'm QCing.

**Comment by mwasham** [comment]
already in the release
