### ISSUE TITLE
Content update scheduled

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Linux-lift-and-shift#12]
This workshop is scheduled for a November update. Please review the contents of this repo and comment on this issue with suggested updates. All suggestions must be added to this issue by EOD November 12, 2018.

**Comment by mwasham** [comment]
Update screenshots and steps
Update to GA Azure DB for MySQL - introduce backup requirements
Add Azure App GW
Add Use Azure Monitor, Securiity Center, and Log Analytics

**Comment by DawnmarieDesJardins** [comment]
Please move forward with this update.  SME review will be requested when PR is ready.

**Comment by DawnmarieDesJardins** [comment]
Issues addressed with Dec 2018 update. Closing issue.
