### ISSUE TITLE
Before the HOL

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Linux-lift-and-shift#2]
Task 3 - Two steps.  Is that correct?  I added the "you should follow all steps provided..." sentence after step 2 but it ends so abruptly I wanted you to look and make sure there's nothing missing please.

Line 148 - In .md, the code reads:  … into the directory **C:\\HOL**  
When looking at the GitHub repo, it shows up with only one back slash - C:\HOL.  Is that okay?

**Comment by mwasham** [comment]
yes, all correct
