### ISSUE TITLE
Problem with custom script extension for linux during OnPrem VM deployment

### ISSUE THREAD

**Issue by rodrigoffonseca** [Microsoft/MCW-Linux-lift-and-shift#9]
Hi, I'm CSA based in Brazil and we would like to use this content in the next partner bootcamp for OSS track.
I testing the HOL lab and I got an error during the template deployment for the OnPrem VM:
az group deployment create --name OsTicketOnPremRG --resource-group OsTicketOnPremRG --template-uri "https://cloudworkshop.blob.core.windows.net/linux-lift-shift/onpremvmdeploy.json"

Deployment failed. Correlation ID: 88c45ed5-f624-48e8-a705-5b36c8c5604e. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'CustomSciptExtension1'. Error message: \"Command returned an error.\n---stdout---\n 404  Not Found\nErr:39 http://security.ubuntu.com/ubuntu xenial-security/main amd64 php7.0-mysql amd64 7.0.30-0ubuntu0.16.04.1\n  404  Not Found\nFetched 21.0 MB in 1s (13.2 MB/s)\nReading package lists...\nBuilding dependency tree...\nReading state information...\nSuggested packages:\n  zip\nThe following NEW packages will be installed:\n  unzip\n0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 158 kB of archives.\nAfter this operation, 530 kB of additional disk space will be used.\nGet:1 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 unzip amd64 6.0-20ubuntu1 [158 kB]\nFetched 158 kB in 0s (0 B/s)\nSelecting previously unselected package unzip.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 55052 files and directories currently installed.)\r\nPreparing to unpack .../unzip_6.0-20ubuntu1_amd64.deb ...\r\nUnpacking unzip (6.0-20ubuntu1) ...\r\nProcessing triggers for mime-support (3.59ubuntu1) ...\r\nProcessing triggers for man-db (2.7.5-1) ...\r\nSetting up unzip (6.0-20ubuntu1) ...\r\nHit:1 http://azure.archive.ubuntu.com/ubuntu xenial InRelease\nGet:2 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]\nGet:3 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]\nGet:4 http://azure.archive.ubuntu.com/ubuntu xenial/main Sources [868 kB]\nGet:5 http://azure.archive.ubuntu.com/ubuntu xenial/restricted Sources [4,808 B]\nGet:6 http://azure.archive.ubuntu.com/ubuntu xenial/universe Sources [7,728 kB]\nGet:7 http://azure.archive.ubuntu.com/ubuntu xenial/multiverse Sources [179 kB]\nGet:8 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main Sources [321 kB]\nGet:9 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]\nGet:10 http://azure.archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [2,528 B]\nGet:11 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe Sources [222 kB]\nGet:12 http://azure.archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [8,388 B]\nGet:13 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [849 kB]\nGet:14 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [347 kB]\nGet:15 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [691 kB]\nGet:16 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [279 kB]\nGet:17 http://azure.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.4 kB]\nGet:18 http://azure.archive.ubuntu.com/ubuntu xenial-backports/main Sources [4,488 B]\nGet:19 http://azure.archive.ubuntu.com/ubuntu xenial-backports/universe Sources [6,740 B]\nGet:20 http://azure.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7,568 B]\nGet:21 http://azure.archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [4,048 B]\nGet:22 http://security.ubuntu.com/ubuntu xenial-security/main Sources [134 kB]\nGet:23 http://security.ubuntu.com/ubuntu xenial-security/restricted Sources [2,116 B]\nGet:24 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [75.8 kB]\nGet:25 http://security.ubuntu.com/ubuntu xenial-security/multiverse Sources [2,088 B]\nGet:26 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [556 kB]\nGet:27 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [235 kB]\nGet:28 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [379 kB]\nGet:29 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [144 kB]\nFetched 13.4 MB in 2s (5,352 kB/s)\nReading package lists...\nArchive:  osticket.zip\n\n---errout---\n.......... .......... .......... .......... .......... 71%  132M 0s\n  6000K .......... .......... .......... .......... .......... 72%  193M 0s\n  6050K .......... .......... .......... .......... .......... 72%  224M 0s\n  6100K .......... .......... .......... .......... .......... 73%  200M 0s\n  6150K .......... .......... .......... .......... .......... 73%  126M 0s\n  6200K .......... .......... .......... .......... .......... 74%  196M 0s\n  6250K .......... .......... .......... .......... .......... 75%  300M 0s\n  6300K .......... .......... .......... .......... .......... 75%  119M 0s\n  6350K .......... .......... .......... .......... .......... 76%  167M 0s\n  6400K .......... .......... .......... .......... .......... 76%  233M 0s\n  6450K .......... .......... .......... .......... .......... 77%  185M 0s\n  6500K .......... .......... .......... .......... .......... 78%  153M 0s\n  6550K .......... .......... .......... .......... .......... 78%  160M 0s\n  6600K .......... .......... .......... .......... .......... 79%  186M 0s\n  6650K .......... .......... .......... .......... .......... 79%  223M 0s\n  6700K .......... .......... .......... .......... .......... 80%  164M 0s\n  6750K .......... .......... .......... .......... .......... 80%  177M 0s\n  6800K .......... .......... .......... .......... .......... 81%  225M 0s\n  6850K .......... .......... .......... .......... .......... 82%  230M 0s\n  6900K .......... .......... .......... .......... .......... 82%  152M 0s\n  6950K .......... .......... .......... .......... .......... 83%  152M 0s\n  7000K .......... .......... .......... .......... .......... 83%  189M 0s\n  7050K .......... .......... .......... .......... .......... 84%  158M 0s\n  7100K .......... .......... .......... .......... .......... 85%  148M 0s\n  7150K .......... .......... .......... .......... .......... 85%  222M 0s\n  7200K .......... .......... .......... .......... .......... 86%  215M 0s\n  7250K .......... .......... .......... .......... .......... 86%  148M 0s\n  7300K .......... .......... .......... .......... .......... 87%  199M 0s\n  7350K .......... .......... .......... .......... .......... 88%  170M 0s\n  7400K .......... .......... .......... .......... .......... 88%  142M 0s\n  7450K .......... .......... .......... .......... .......... 89%  267M 0s\n  7500K .......... .......... .......... .......... .......... 89%  252M 0s\n  7550K .......... .......... .......... .......... .......... 90%  170M 0s\n  7600K .......... .......... .......... .......... .......... 91%  151M 0s\n  7650K .......... .......... .......... .......... .......... 91%  157M 0s\n  7700K .......... .......... .......... .......... .......... 92%  224M 0s\n  7750K .......... .......... .......... .......... .......... 92%  199M 0s\n  7800K .......... .......... .......... .......... .......... 93%  173M 0s\n  7850K .......... .......... .......... .......... .......... 94%  175M 0s\n  7900K .......... .......... .......... .......... .......... 94%  233M 0s\n  7950K .......... .......... .......... .......... .......... 95%  189M 0s\n  8000K .......... .......... .......... .......... .......... 95%  204M 0s\n  8050K .......... .......... .......... .......... .......... 96%  277M 0s\n  8100K .......... .......... .......... .......... .......... 97%  321M 0s\n  8150K .......... .......... .......... .......... .......... 97%  283M 0s\n  8200K .......... .......... .......... .......... .......... 98%  329M 0s\n  8250K .......... .......... .......... .......... .......... 98%  229M 0s\n  8300K .......... .......... .......... .......... .......... 99%  290M 0s\n  8350K .......... .......... .......... .......... .......   100%  284M=0.1s\n\n2018-09-26 18:56:38 (70.6 MB/s) - osticket.zip saved [8598701/8598701]\n\ncheckdir:  cannot create extraction directory: /var/www/html\n           No such file or directory\nchown: cannot access '/var/www/html': No such file or directory\nmv: cannot stat '/var/www/html/index.html': No such file or directory\nFailed to restart apache2.service: Unit apache2.service not found.\n\n\"."
      }
    ]
  }
}

From what I found out it seems that line:
sudo apt-get install -y lamp-server^
is not working and installing the required components. When I manually run the script after the extension error I was able to successfully start the application.

**Comment by DawnmarieDesJardins** [comment]
Hi Michael, please review and make sure this was resolved with the September test/fix I'm QCing.

**Comment by mwasham** [comment]
The lab worked in the Sept test/fix branch so this should be resolved since it was tested against the old branch
